volumes:
  pg_data:

services:
  db:
    image: postgres
    env_file:
      - ./.env
    volumes:
      - pg_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  web:
    build: .
    command: "sh -c 'alembic upgrade head && uvicorn app.main:app --reload --workers 3 --host 0.0.0.0 --port 8000'"
    env_file:
      - ./.env
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always