"""postgresq1l

Revision ID: 3d1288155a8b
Revises: f69d2c93190a
Create Date: 2024-08-22 22:23:34.912089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d1288155a8b'
down_revision = 'f69d2c93190a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
