"""postgresql3

Revision ID: 53116f102840
Revises: 60221e54f7ce
Create Date: 2024-08-22 22:28:25.415617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53116f102840'
down_revision = '60221e54f7ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
