"""postgresql1

Revision ID: 60221e54f7ce
Revises: 3d1288155a8b
Create Date: 2024-08-22 22:24:41.445006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60221e54f7ce'
down_revision = '3d1288155a8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
