"""First

Revision ID: 827f2a5d3857
Revises: 233d745c2de8
Create Date: 2024-08-22 23:14:22.815767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '827f2a5d3857'
down_revision = '233d745c2de8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
