"""postgresql

Revision ID: f69d2c93190a
Revises: 1b07170c64e0
Create Date: 2024-08-22 22:21:24.447277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f69d2c93190a'
down_revision = '1b07170c64e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
